// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function($) {
  var jar;
  jar = require('jar');
  jar.Jar = (function(_super) {

    __extends(Jar, _super);

    function Jar() {
      return Jar.__super__.constructor.apply(this, arguments);
    }

    Jar.prototype._getCookies = function() {
      return document.cookie;
    };

    Jar.prototype._setCookie = function(cookie) {
      document.cookie = cookie.toString();
    };

    Jar.prototype.get = function() {
      this.parse();
      return Jar.__super__.get.apply(this, arguments);
    };

    Jar.prototype.set = function() {
      this.parse();
      return Jar.__super__.set.apply(this, arguments);
    };

    return Jar;

  })(jar.Jar);
  return $.ender({
    jar: new jar.Jar,
    cookie: function(name, value, options) {
      if (value != null) {
        return $.jar.set(name, value, options);
      } else {
        return $.jar.get(name);
      }
    }
  });
})(ender);
